# Generated by Django 5.2.5 on 2025-10-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='transaction_pin',
            new_name='pin_hash',
        ),
    ]
