providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[phases.setup]
# Python + pip from Nix + build toolchain for psycopg2
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "gcc",
  "libffi",
  "openssl",
  "zlib",
  "postgresql",
  "pkg-config"
]
# ensurepip is harmless if pip already present
cmds = ["python3 -m ensurepip --upgrade || true"]

[phases.install]
cmds = [
  "pip3 install --upgrade pip setuptools wheel",
  "pip3 install -r requirements.txt"
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:${PORT} --log-file -"
