providers = ["python"]

[phases.setup]
# Python + toolchain for psycopg2/Pillow/etc.
nixPkgs = ["python311", "gcc", "libffi", "openssl", "zlib", "postgresql"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
# Run DB migrations at start, then launch Gunicorn on the port Railway provides
cmd = "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:${PORT} --log-file -"
