providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[phases.setup]
# Python + toolchain; then create our own venv so PEP 668 doesn't block pip
nixPkgs = [
  "python311",
  "gcc",
  "libffi",
  "openssl",
  "zlib",
  "postgresql",
  "pkg-config"
]
cmds = [
  "python3 -m venv /opt/venv"
]

[phases.install]
# Use the venv’s pip/python, never the system ones
cmds = [
  "/opt/venv/bin/python -m pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "/opt/venv/bin/python manage.py collectstatic --noinput"
]

[start]
cmd = "export DJANGO_SUPERUSER_USERNAME=EnohenseAdmin && export DJANGO_SUPERUSER_EMAIL=williamssandra803@gmail.com && export DJANGO_SUPERUSER_PASSWORD=s@ndR@! && /opt/venv/bin/python manage.py migrate && /opt/venv/bin/python manage.py createsuperuser --noinput && /opt/venv/bin/gunicorn config.wsgi:application --bind 0.0.0.0:${PORT} --log-file -"
