providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[phases.setup]
# Python + toolchain for psycopg2
nixPkgs = ["python311", "gcc", "libffi", "openssl", "zlib", "postgresql", "pkg-config"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip wheel setuptools",
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:${PORT} --log-file -"
